FROM node:18-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

FROM node:18-alpine AS release

WORKDIR /app

COPY --from=build /app/dist /app/dist
COPY package*.json ./
RUN npm install --production

EXPOSE 3000


CMD ["node", "dist/index.js"]

